Feat/remove default values
hadronlabs-org/drop-contracts pull request #109
Opened 2024-07-03 19:57 UTC by faust403

2024-07-08 10:59 UTC, albertandrejev commented on scripts/deploy_scripts/utils.bash
> +      "icq_update_delay": 5
Please replace these default values with variables as well

2024-07-08 10:59 UTC, albertandrejev commented on scripts/deploy_scripts/utils.bash
> +      "idle_min_interval":60,
This one as well

2024-07-08 10:59 UTC, albertandrejev commented on scripts/deploy_scripts/utils.bash
> +      "update_period":100
here

2024-07-08 10:59 UTC, albertandrejev commented on scripts/deploy_scripts/utils.bash
> +      "symbol":"DROP"
This values as well, but set default value to the current constant

2024-07-08 10:59 UTC, albertandrejev commented on scripts/deploy_scripts/utils.bash
> +      "min_ibc_transfer":"10000",
and here

2024-07-09 08:41 UTC, albertandrejev requested changes

2024-07-09 08:41 UTC, albertandrejev commented on scripts/deploy_scripts/instantiate.bash
> +TOKEN_METADATA_SYMBOL="${TOKEN_METADATA_SYMBOL:?Variable should explicitly specified}"
These values can have default values, please use previous hard coded values as defaults for this variables

2024-07-09 10:51 UTC, albertandrejev approved these changes

2024-07-09 11:30 UTC, ratik approved these changes

2024-07-10 15:20 UTC, closed without merging