Exchange rate checker
hadronlabs-org/drop-contracts pull request #119
Opened 2024-07-17 15:37 UTC by faust403

2024-07-28 17:28 UTC, foxpy commented on yarn.lock
Should this file really be here?

2024-08-01 14:58 UTC, ratik requested changes

2024-08-01 14:58 UTC, ratik commented on integration_tests/src/helpers/exchangeRate.ts
> +  const { coreContractClient, client, neutronRPCEndpoint } = testContext;
please use coreContractClient, puppeterContractClient, etc to query data. no need to connect once again

2024-08-01 14:58 UTC, ratik commented on integration_tests/package.json
> +    "calc-exchange-rate": "ts-node ./src/helpers/exchangeRate.ts",
why?

2024-08-02 09:33 UTC, foxpy approved these changes

2024-08-02 10:33 UTC, ratik commented on integration_tests/src/helpers/exchangeRate.ts
> +  const queryService = new QueryClientImpl(RPC);
you can use neutronClient for this purpose I believe

2024-08-05 08:37 UTC, merged