Feat: DRP-339. Remove BONDED_AMOUNT
hadronlabs-org/drop-contracts pull request #167
Opened 2024-08-21 17:33 UTC by albertandrejev

2024-08-28 18:35 UTC, foxpy approved these changes

2024-08-28 20:14 UTC, foxpy commented on contracts/core/src/contract.rs
> +    let exchange_rate_denominator = ld_total_supply.amount.amount;
This variable is being shadowed on line 211. That's 100% wrong. You shouldn't define denominator this early in this function.

2024-08-28 20:17 UTC, foxpy requested changes
Other than incorrect exchange rate calculation, everything looks good for me

2024-08-28 20:21 UTC, foxpy approved these changes

2024-09-10 22:49 UTC, foxpy approved these changes
At this point, shouldn't we point this PR into `dev` branch instead?

2024-09-24 08:31 UTC, ratik approved these changes

2024-09-24 08:33 UTC, merged